# Generated by Django 5.0.1 on 2026-04-30 20:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionProblem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('goal', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('in_progress', 'En cours'), ('completed', 'Complété')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('criterion_type', models.CharField(choices=[('quantitative', 'Quantitatif'), ('categorical', 'Catégorique')], default='quantitative', max_length=20)),
                ('scale_type', models.CharField(choices=[('linear', 'Linéaire'), ('logarithmic', 'Logarithmique'), ('custom', 'Personnalisé')], default='linear', max_length=20)),
                ('weight', models.FloatField(default=0.0)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='problems.decisionproblem')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('final_score', models.FloatField(default=0.0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='problems.decisionproblem')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScalePreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('numeric_value', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scale_preferences', to='problems.criterion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AlternativeScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numeric_score', models.FloatField(blank=True, null=True)),
                ('categorical_value', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='problems.alternative')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.criterion')),
                ('scale_preference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='problems.scalepreference')),
            ],
        ),
        migrations.AddIndex(
            model_name='decisionproblem',
            index=models.Index(fields=['created_by', '-created_at'], name='problems_de_created_a605ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='criterion',
            unique_together={('problem', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='alternative',
            unique_together={('problem', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='scalepreference',
            unique_together={('criterion', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='alternativescore',
            unique_together={('alternative', 'criterion')},
        ),
    ]
