# Generated by Django 4.2.7 on 2026-04-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='direction',
            field=models.CharField(choices=[('benefit', "Plus c'est grand, mieux c'est"), ('cost', "Plus c'est petit, mieux c'est")], default='benefit', max_length=10),
        ),
    ]
