events {}
http {
    include /etc/nginx/mime.types;
    
    server {
        listen 80;

        # Frontend React
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # Backend Django API
        location /api/ {
            proxy_pass http://127.0.0.1:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Django Admin
        location /admin/ {
            proxy_pass http://127.0.0.1:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Fichiers statiques Django
        location /static/ {
            alias /app/staticfiles/;
        }
    }
}
