services:
  - type: web
    name: ahp-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: https://ahp-app.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: ahp-db
          property: connectionString

databases:
  - name: ahp-db
    databaseName: ahp_db
    user: ahp_user
    plan: free
    region: frankfurt
