# Generated by Django 5.0.1 on 2026-04-30 20:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criteria_weights', models.JSONField()),
                ('alternative_scores', models.JSONField()),
                ('ranking', models.JSONField()),
                ('best_alternative_id', models.CharField(max_length=255)),
                ('best_alternative_name', models.CharField(max_length=255)),
                ('best_alternative_score', models.FloatField()),
                ('is_consistent', models.BooleanField(default=False)),
                ('consistency_ratio', models.FloatField(blank=True, null=True)),
                ('inconsistency_reasons', models.JSONField(default=list)),
                ('average_score', models.FloatField()),
                ('std_deviation', models.FloatField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='problems.decisionproblem')),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matrix_type', models.CharField(choices=[('criteria', 'Comparaison de Critères')], default='criteria', max_length=20)),
                ('dimension', models.IntegerField()),
                ('matrix_data', models.JSONField()),
                ('normalized_data', models.JSONField(blank=True, null=True)),
                ('weights', models.JSONField(blank=True, null=True)),
                ('lambda_max', models.FloatField(blank=True, null=True)),
                ('consistency_index', models.FloatField(blank=True, null=True)),
                ('consistency_ratio', models.FloatField(blank=True, null=True)),
                ('is_consistent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_matrices', to='problems.decisionproblem')),
            ],
            options={
                'unique_together': {('problem', 'matrix_type')},
            },
        ),
    ]
