# Generated by Django 4.2.7 on 2026-04-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='alternative_scores_raw',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='consistency_details',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='criteria_matrix',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='criteria_matrix_normalized',
            field=models.JSONField(null=True),
        ),
    ]
