# Generated by Django 4.2.7 on 2026-04-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysisresult_alternative_scores_raw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='criteria_column_sums',
            field=models.JSONField(null=True),
        ),
    ]
