# Generated by Django 4.2.7 on 2026-04-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_analysisresult_criteria_column_sums'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonmatrix',
            name='column_sums',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
