# Generated by Django 4.2.7 on 2026-04-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_comparisonmatrix_column_sums'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='criteria_row_sums',
            field=models.JSONField(null=True),
        ),
    ]
