# Generated by Django 4.2.7 on 2026-04-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_analysisresult_criteria_row_sums'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonmatrix',
            name='row_sums',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
